# BASE
NAME = 'eden'
SECRET_KEY = 'IuFWKUut'

# DB
DATABASE = 'D:/code/eden.db'
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = 'sqlite:///' + DATABASE

DEBUG = True
